name: Update and deploy
# Everyday attempt to update Lean and mathlib. If the update succeeds then deploy the updated version to the webpage.

on:
  schedule:
    - cron: "0 8 * * *" # every day at 8:00 UTC
  workflow_dispatch: # allows workflow to be triggered manually

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.update-tactic-list.outputs.files_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Lean project
        id: update-lean-mathlib
        uses: oliver-butterley/lean-update@v1-alpha

      - name: debug
        run: echo ${{ steps.update-lean-mathlib.outputs.result }}

      - name: When update succeeds generate markdown file
        if: steps.update-lean-mathlib.outputs.result == 'update-success'
        id: update-tactic-list
        run: |
          lake env lean --run Main.lean > src/tactics.md
          python3 script.py
          git add .
          echo "debug info:"
          git diff -w "src/tactics.md"
          git diff --name-only
          echo "debug info end"
          if [[ -n $(git diff -w "src/tactics.md") ]]; then
            echo "files_changed=true"  >> "$GITHUB_OUTPUT"
           else
            echo "files_changed=false" >> "$GITHUB_OUTPUT"
          fi
          cat "$GITHUB_OUTPUT"

  deploy:
    if: needs.update.outputs.updated == true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update
    steps:
      - name: Commit updated version
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Updated version from cron job"
          git push
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_ACTOR_ID: ${{ github.actor_id }}

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.32"

      - name: Build mdbook
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./book
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
